using LocalMindAI.Api.Data; using LocalMindAI.Api.DTOs; using Microsoft.EntityFrameworkCore;
namespace LocalMindAI.Api.Services;
public sealed class AnalyticsService(ApplicationDbContext db) : IAnalyticsService
{
    private static (DateTime Start,DateTime End) Range(AnalyticsRangeQuery q){var end=(q.EndDate??DateTime.UtcNow).Date.AddDays(1);var start=q.StartDate?.Date??q.Period switch{"today"=>end.AddDays(-1),"7d"=>end.AddDays(-7),"90d"=>end.AddDays(-90),_=>end.AddDays(-30)};return(start,end);}
    private static AnalyticsDto Data((DateTime Start,DateTime End) r,Dictionary<string,object?> m,IReadOnlyList<AnalyticsPointDto>? s=null,IReadOnlyList<AnalyticsSliceDto>? d=null)=>new(){StartDate=r.Start,EndDate=r.End.AddTicks(-1),Metrics=m,Series=s??[],Distribution=d??[]};
    public async Task<AnalyticsDto> OverviewAsync(AnalyticsRangeQuery q,CancellationToken c=default){var r=Range(q);var customers=db.Customers.AsNoTracking();var reviews=db.Reviews.AsNoTracking();var posts=db.GoogleBusinessPosts.AsNoTracking();var executions=db.WorkflowExecutions.AsNoTracking();var agents=db.Agents.AsNoTracking();return Data(r,new(){["totalCustomers"]=await customers.CountAsync(c),["newCustomers"]=await customers.CountAsync(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["activeCustomers"]=await customers.CountAsync(x=>x.Status!="Lost",c),["reviewsReceived"]=await reviews.CountAsync(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["reviewsReplied"]=await reviews.CountAsync(x=>x.IsReplied&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["postsPublished"]=await posts.CountAsync(x=>x.Status=="Published"&&x.PublishedTime>=r.Start&&x.PublishedTime<r.End,c),["postsScheduled"]=await posts.CountAsync(x=>x.Status=="Scheduled",c),["workflowExecutions"]=await executions.CountAsync(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["successfulWorkflows"]=await executions.CountAsync(x=>x.Status=="Completed"&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["failedWorkflows"]=await executions.CountAsync(x=>x.Status=="Failed"&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["aiRequests"]=null,["activeAiAgents"]=await agents.CountAsync(x=>x.Status=="Running",c)});}
    public async Task<AnalyticsDto> CustomersAsync(AnalyticsRangeQuery q,CancellationToken c=default){var r=Range(q);var rows=await db.Customers.AsNoTracking().Where(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End).GroupBy(x=>x.CreatedAt.Date).Select(g=>new AnalyticsPointDto{Date=g.Key,Value=g.Count()}).ToListAsync(c);var dist=await db.Customers.AsNoTracking().GroupBy(x=>x.Status).Select(g=>new AnalyticsSliceDto{Name=g.Key,Value=g.Count()}).ToListAsync(c);return Data(r,new(){["totalCustomers"]=await db.Customers.CountAsync(c),["newCustomers"]=(decimal?)rows.Sum(x=>x.Value),["customerActivity"]=await db.CustomerActivities.AsNoTracking().CountAsync(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c)},rows,dist);}
    public async Task<AnalyticsDto> ReviewsAsync(AnalyticsRangeQuery q,CancellationToken c=default){var r=Range(q);var rows=await db.Reviews.AsNoTracking().Where(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End).GroupBy(x=>x.CreatedAt.Date).Select(g=>new AnalyticsPointDto{Date=g.Key,Value=g.Count()}).ToListAsync(c);var ratings=await db.Reviews.AsNoTracking().GroupBy(x=>x.Rating).Select(g=>new AnalyticsSliceDto{Name=$"{g.Key} stars",Value=g.Count()}).ToListAsync(c);var avg=await db.Reviews.AsNoTracking().Select(x=>(decimal?)x.Rating).AverageAsync(c);return Data(r,new(){["totalReviews"]=(decimal?)rows.Sum(x=>x.Value),["replied"]=await db.Reviews.AsNoTracking().CountAsync(x=>x.IsReplied&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["unreplied"]=await db.Reviews.AsNoTracking().CountAsync(x=>!x.IsReplied&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["averageRating"]=avg},rows,ratings);}
    public async Task<AnalyticsDto> PostsAsync(AnalyticsRangeQuery q,CancellationToken c=default){var r=Range(q);var rows=await db.GoogleBusinessPosts.AsNoTracking().Where(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End).GroupBy(x=>x.CreatedAt.Date).Select(g=>new AnalyticsPointDto{Date=g.Key,Value=g.Count()}).ToListAsync(c);var dist=await db.GoogleBusinessPosts.AsNoTracking().GroupBy(x=>x.Status).Select(g=>new AnalyticsSliceDto{Name=g.Key,Value=g.Count()}).ToListAsync(c);return Data(r,new(){["totalPosts"]=await db.GoogleBusinessPosts.CountAsync(c),["published"]=await db.GoogleBusinessPosts.CountAsync(x=>x.Status=="Published",c),["scheduled"]=await db.GoogleBusinessPosts.CountAsync(x=>x.Status=="Scheduled",c),["drafts"]=await db.GoogleBusinessPosts.CountAsync(x=>x.Status=="Draft",c),["failed"]=await db.GoogleBusinessPosts.CountAsync(x=>x.Status=="Failed",c)},rows,dist);}
    public async Task<AnalyticsDto> WorkflowsAsync(AnalyticsRangeQuery q,CancellationToken c=default){var r=Range(q);var rows=await db.WorkflowExecutions.AsNoTracking().Where(x=>x.CreatedAt>=r.Start&&x.CreatedAt<r.End).GroupBy(x=>x.CreatedAt.Date).Select(g=>new AnalyticsPointDto{Date=g.Key,Value=g.Count()}).ToListAsync(c);var dist=await db.WorkflowExecutions.AsNoTracking().GroupBy(x=>x.Status).Select(g=>new AnalyticsSliceDto{Name=g.Key,Value=g.Count()}).ToListAsync(c);var durations=await db.WorkflowExecutions.AsNoTracking().Where(x=>x.CompletedAt!=null&&x.StartedAt!=null).Select(x=>EF.Functions.DateDiffSecond(x.StartedAt!.Value,x.CompletedAt!.Value)).ToListAsync(c);return Data(r,new(){["totalExecutions"]=(decimal?)rows.Sum(x=>x.Value),["successful"]=await db.WorkflowExecutions.CountAsync(x=>x.Status=="Completed"&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["failed"]=await db.WorkflowExecutions.CountAsync(x=>x.Status=="Failed"&&x.CreatedAt>=r.Start&&x.CreatedAt<r.End,c),["running"]=await db.WorkflowExecutions.CountAsync(x=>x.Status=="Running",c),["averageDurationSeconds"]=durations.Count==0?null:durations.Average()},rows,dist);}
    public async Task<AnalyticsDto> AgentsAsync(AnalyticsRangeQuery q,CancellationToken c=default){var dist=await db.Agents.AsNoTracking().GroupBy(x=>x.Status).Select(g=>new AnalyticsSliceDto{Name=g.Key,Value=g.Count()}).ToListAsync(c);return Data(Range(q),new(){["totalAgents"]=await db.Agents.CountAsync(c),["activeAgents"]=await db.Agents.CountAsync(x=>x.Status=="Running",c),["pausedAgents"]=await db.Agents.CountAsync(x=>x.Status=="Paused",c),["failedExecutions"]=null},[],dist);}
    public Task<AnalyticsDto> AiUsageAsync(AnalyticsRangeQuery q,CancellationToken c=default)=>Task.FromResult(Data(Range(q),new(){["aiRequests"]=null,["agentExecutions"]=null,["agentSuccess"]=null,["agentFailures"]=null,["tokens"]=null,["cost"]=null}));
    public Task<AnalyticsDto> RevenueAsync(AnalyticsRangeQuery q,CancellationToken c=default)=>Task.FromResult(Data(Range(q),new(){["revenue"]=null}));
}
