using System.Net.Http.Headers;
using System.Text.Json;
using LocalMindAI.Api.Data;
using LocalMindAI.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace LocalMindAI.Api.Services;
public interface IGoogleBusinessProfileService { string AuthorizationUrl(string redirectUri); Task CompleteOAuthAsync(string code, string redirectUri); Task<object> AccountsAsync(); Task<object> LocationsAsync(); Task<object> SyncAsync(); Task DisconnectAsync(int accountId); Task<object> OverviewAsync(); }
public class GoogleBusinessProfileService(ApplicationDbContext context, IHttpClientFactory clients, IConfiguration config) : IGoogleBusinessProfileService
{
 public string AuthorizationUrl(string redirectUri) { var id = config["GoogleBusiness:ClientId"] ?? throw new InvalidOperationException("GoogleBusiness:ClientId is required."); return $"https://accounts.google.com/o/oauth2/v2/auth?client_id={Uri.EscapeDataString(id)}&redirect_uri={Uri.EscapeDataString(redirectUri)}&response_type=code&scope={Uri.EscapeDataString("openid email https://www.googleapis.com/auth/business.manage")}&access_type=offline&prompt=consent"; }
 public async Task CompleteOAuthAsync(string code, string redirectUri) { var client = clients.CreateClient(); var token = await client.PostAsync("https://oauth2.googleapis.com/token", new FormUrlEncodedContent(new Dictionary<string,string> { ["code"] = code, ["client_id"] = config["GoogleBusiness:ClientId"]!, ["client_secret"] = config["GoogleBusiness:ClientSecret"]!, ["redirect_uri"] = redirectUri, ["grant_type"] = "authorization_code" })); token.EnsureSuccessStatusCode(); using var doc = JsonDocument.Parse(await token.Content.ReadAsStringAsync()); var access = doc.RootElement.GetProperty("access_token").GetString()!; var refresh = doc.RootElement.TryGetProperty("refresh_token", out var refreshValue) ? refreshValue.GetString() ?? "" : ""; var profileRequest = new HttpRequestMessage(HttpMethod.Get, "https://www.googleapis.com/oauth2/v3/userinfo"); profileRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", access); var profileResponse = await client.SendAsync(profileRequest); profileResponse.EnsureSuccessStatusCode(); using var profile = JsonDocument.Parse(await profileResponse.Content.ReadAsStringAsync()); var email = profile.RootElement.GetProperty("email").GetString()!; var account = await context.GoogleBusinessAccounts.FirstOrDefaultAsync(x => x.Email == email) ?? new GoogleBusinessAccount { Email = email, GoogleAccountId = profile.RootElement.GetProperty("sub").GetString()! }; account.AccessToken = access; account.RefreshToken = refresh; account.TokenExpiresAt = DateTime.UtcNow.AddSeconds(doc.RootElement.GetProperty("expires_in").GetInt32()); if (account.Id == 0) context.GoogleBusinessAccounts.Add(account); await context.SaveChangesAsync(); await SyncAsync(); }
 public async Task<object> AccountsAsync() => await context.GoogleBusinessAccounts.AsNoTracking().Select(x => new { x.Id, x.Email, x.ConnectedAt, x.TokenExpiresAt }).ToListAsync();
 public async Task<object> LocationsAsync() => await context.GoogleBusinessLocations.AsNoTracking().Select(x => new { x.Id, x.AccountId, x.Name, x.Address, x.LastSyncedAt }).ToListAsync();
 public async Task<object> SyncAsync() { var accounts = await context.GoogleBusinessAccounts.ToListAsync(); foreach (var account in accounts) { if (account.TokenExpiresAt <= DateTime.UtcNow && !string.IsNullOrWhiteSpace(account.RefreshToken)) await RefreshAsync(account); } await context.SaveChangesAsync(); return new { status = "Synchronized", accountCount = accounts.Count, completedAt = DateTime.UtcNow }; }
 public async Task DisconnectAsync(int accountId) { var account = await context.GoogleBusinessAccounts.FindAsync(accountId) ?? throw new KeyNotFoundException("Google account was not found."); context.GoogleBusinessLocations.RemoveRange(context.GoogleBusinessLocations.Where(x => x.AccountId == accountId)); context.GoogleBusinessAccounts.Remove(account); await context.SaveChangesAsync(); }
 public async Task<object> OverviewAsync() => new { accounts = await AccountsAsync(), locations = await LocationsAsync() };
 private async Task RefreshAsync(GoogleBusinessAccount account) { var response = await clients.CreateClient().PostAsync("https://oauth2.googleapis.com/token", new FormUrlEncodedContent(new Dictionary<string,string> { ["client_id"] = config["GoogleBusiness:ClientId"]!, ["client_secret"] = config["GoogleBusiness:ClientSecret"]!, ["refresh_token"] = account.RefreshToken, ["grant_type"] = "refresh_token" })); response.EnsureSuccessStatusCode(); using var doc = JsonDocument.Parse(await response.Content.ReadAsStringAsync()); account.AccessToken = doc.RootElement.GetProperty("access_token").GetString()!; account.TokenExpiresAt = DateTime.UtcNow.AddSeconds(doc.RootElement.GetProperty("expires_in").GetInt32()); }
}
